name: Test
on: 
    workflow_dispatch:
      inputs:
        branch-name:
          type: choice
          description: Who to greet
          options: 
          - master
          - main
          - uat
          - dev
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Environment
        run: |
          branch=${{ github.base_ref || github.ref_name }}
          if [[ "$branch" == "master" || "$branch" == "main" ]]; then
            echo "branch_name=PRD" >> $GITHUB_ENV
          else
            echo "branch_name=${branch^^}" >> $GITHUB_ENV
          fi
      - name: Set Role
        run: echo ${{ format('ECR-{0}-ROLE', env.branch_name) }}
        env:
          ECR-ROLE: ${{ format('ECR-{0}-ROLE', env.branch_name) }}
      - name: d
        run: echo ${{ env.branch_name }}
  
      - name: hey
        run: echo ${{ env.ECR-ROLE }}
  
      