name: PHPMD Analysis

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  phpmd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Adjust PHP version if needed
          tools: phpmd

      - name: Run PHPMD
        run: phpmd . xml cleancode --reportfile phpmd-report.xml --ignore-violations-on-exit

      - name: Convert XML to JSON
        run: |
          php -r '$xml = simplexml_load_file("phpmd-report.xml"); echo json_encode($xml, JSON_PRETTY_PRINT);' > phpmd-report.json

      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPORT=$(cat phpmd-report.json)
          ISSUES=$(echo "$REPORT" | jq -r '.file[] | select(.violation != null) | "\n- **File:** \(.name)\n  **Violations:**\n" + ( .violation[] | "    - \(.rule): \(.description)" )')

          TITLE="PHPMD Analysis Report"
          BODY="## PHPMD Analysis Results\n\n$ISSUES\n\nPlease review and address these issues."

          PAYLOAD=$(echo '{}' | jq --arg title "$TITLE" --arg body "$BODY" '.title = $title | .body = $body')
          curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -H "Content-Type: application/json" -d "$PAYLOAD" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues"
