name: Create Issue
on:
  workflow_dispatch:

jobs:
  create_issue:
    name: Create Mess Issue
    runs-on: ubuntu-latest
    

    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: phpmd/phpmd
      - name: Mess Detection
        run: |
          ~/.composer/vendor/bin/phpmd . json cleancode --suffixes php --exclude vendor,tests | 
          mess=jq -c '.files[] | .file as $file | .violations[] | "- [ ] [\(.description)](\($file)#L\(.beginLine))"'

          echo "mess-detection=$mess" >> $GITHUB_ENV
          
      - name: Create team sync issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Test
          ASSIGNEES: landonpatterson-tyler
          LABELS: enhancement
          BODY: |
            ### Messes

            ${{ env.mess-detection }}
          PINNED: false
          CLOSE_PREVIOUS: true
